[package]
name = "raytracer"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies]
gfx_device_gl = "0.15.3"
gfx_window_glutin = "0.23.0"
gfx = "0.17.1"
glutin = "0.15.0"
image = "0.19.0"