[package]
name = "raytracer"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
gfx = "0.18.2"
gfx_core = "0.9.2"
gfx_device_gl = "0.16.2"
glutin = "0.21.2"
image = "0.22.3"
